tap "daipeihust/tap"
tap "homebrew/bundle"
tap "idoavrah/homebrew"
tap "k1low/tap"
brew "awscli"
brew "azure-cli"
brew "bat"
brew "duti"
brew "eza"
brew "fzf"
brew "ghostscript"
brew "git-delta"
brew "imagemagick"
brew "jq"
brew "k6"
brew "k9s"
brew "mas"
brew "mise"
brew "nkf"
brew "ripgrep"
brew "smartmontools"
brew "swagger-codegen"
brew "terracognita"
brew "wget"
brew "zplug"
brew "daipeihust/tap/im-select"
brew "idoavrah/homebrew/tftui"
brew "k1low/tap/tbls"
cask "adguard"
cask "android-platform-tools"
cask "bitwarden"
cask "cyberduck"
cask "deepl"
cask "docker"
cask "firefox"
cask "font-cascadia-code"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive"
cask "google-japanese-ime"
cask "jetbrains-toolbox"
cask "keka"
cask "maccy"
cask "macvim"
cask "notion"
cask "postman"
cask "powershell"
cask "rectangle"
cask "sourcetree"
cask "stoplight-studio"
cask "tableplus"
cask "visual-studio-code"
cask "xcodes"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
