# ******************************************************************************
# 本ファイルは dotfiles により ~/.config/chezmoi/ へ配置される
# 編集する場合は原本 (dotfiles) 側で実施すること
# ******************************************************************************

# 管理ディレクトリを変更 (default: ~/.local/share/chezmoi/)
sourceDir = "~/repos/dotfiles"

[diff]
    # chezmoi スクリプトを差分検知から除外
    exclude = ["scripts"]
