# ******************************************************************************
# chezmoi 外部リソース定義
# ------------------------------------------------------------------------------
# 対象が存在しなければ git clone、存在すれば git pull が実行される
# ******************************************************************************

# Zsh プラグイン管理
[".zplug"]
type = "git-repo"
url = "https://github.com/zplug/zplug.git"
